import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Layout } from '@/components/layout/Layout';
const posts=[
 {slug:'ai-lead-response-revolution',title:'AI assistance for customer inquiries',category:'AI & Automation',related:'/services/ai-lead-capture'},
 {slug:'five-minute-rule',title:'Planning a useful first response',category:'Lead Generation',related:'/services/ai-lead-capture'},
 {slug:'crm-automation-101',title:'Connecting inquiries to your CRM',category:'AI & Automation',related:'/services/crm-automation'},
 {slug:'medspa-seo-guide',title:'Website planning for medical spas',category:'Lead Generation',related:'/industries/medspas'},
 {slug:'merkadflow-system-explained',title:'How we plan connected systems',category:'AI & Automation',related:'/about/method'},
];
export function BlogPage(){const [category,setCategory]=useState('All');const {slug}=useParams();const post=posts.find(p=>p.slug===slug);return <Layout><section className="public-editorial container-custom"><p className="public-caption">Ideas and articles</p><h1>{slug?(post?.title??'Article not found.'):'Practical ideas for connected systems.'}</h1><p className="public-lead">{slug?(post?'This article is not published yet.':'We could not find an article at this address.'):'Articles are being reviewed. Explore the topics below or read about our current services.'}</p>{slug?<nav className="public-related" aria-label="Related content"><Link to="/blog">All topics</Link>{post&&<Link to={post.related}>Related service or project information →</Link>}</nav>:<><div className="public-filters" role="group" aria-label="Filter article topics">{['All','AI & Automation','Lead Generation','Case Studies'].map(name=><button key={name} type="button" aria-pressed={category===name} onClick={()=>setCategory(name)}>{name}</button>)}</div><div className="public-directory">{posts.filter(p=>category==='All'||p.category===category).map(p=><article key={p.slug}><span aria-hidden="true">↗</span><div><p className="public-caption">{p.category}</p><h2><Link to={`/blog/${p.slug}`}>{p.title}</Link></h2><p>Article awaiting publication review.</p></div></article>)}</div><p className="public-review-note">Newsletter signup is not currently available.</p></>}</section></Layout>}
