import { SystemsReviewLink } from '@/components/brand/SystemsReviewLink';
import { Link, useLocation } from 'react-router-dom';
import { Layout } from '@/components/layout/Layout';
import { ServiceGraphic } from '@/pages/concepts/ServiceGraphic';
import { detailPages, serviceLinks, industryLinks, caseLinks, availability } from './siteContent';
export function PublicDetail() {
 const pathname=useLocation().pathname.replace(/\/+$/, '') || '/'; const page=detailPages[pathname];
 return <Layout><section className="public-editorial container-custom"><div className="public-intro"><div><p className="public-caption">{pathname.split('/')[1]}</p><h1>{page.title}</h1><p className="public-lead">{page.intro}</p><p className="public-availability">{page.status}</p><SystemsReviewLink/></div><div className="public-diagram"><ServiceGraphic kind={page.kind}/><p className="public-caption">Illustrative structure</p></div></div><div className="public-detail-sections">{page.sections.map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}</div><nav className="public-related" aria-label="Related pages">{(page.related??(pathname.startsWith('/industries')?industryLinks:serviceLinks)).filter(([,path])=>path!==pathname).map(([name,path])=><Link to={path} key={path}>{name} <span aria-hidden="true">↗</span></Link>)}</nav></section></Layout>;
}
export function PublicHub(){const pathname=useLocation().pathname.replace(/\/+$/, '') || '/';const services=pathname==='/services'; const links=services?serviceLinks:industryLinks;return <Layout><section className="public-editorial container-custom"><p className="public-caption">{services?'Services':'Industries'}</p><h1>{services?'Build the part your business needs.':'Design around the work you do.'}</h1><p className="public-lead">{services?'Websites, CRM integration and AI-assisted workflows around how your team works.':'Explore how a clearer website and inquiry process can fit your business.'}</p><p className="public-availability">{availability}</p><div className="public-directory">{links.map(([name,path],i)=><article key={path}><span className="public-caption">0{i+1}</span><div><h2><Link to={path}>{name} <span aria-hidden="true">↗</span></Link></h2><p>{detailPages[path].intro}</p><small>{detailPages[path].status}</small></div><ServiceGraphic kind={String(i%3+1).padStart(2,'0')}/></article>)}</div></section></Layout>}
export function EvidencePage(){const pathname=useLocation().pathname.replace(/\/+$/, '') || '/';const title=caseLinks.find(([,path])=>path===pathname)?.[0]??(pathname==='/portfolio'?'Project portfolio':pathname==='/results'?'Results and project evidence':'Case studies');return <Layout><section className="public-editorial container-custom"><p className="public-caption">Project information</p><h1>{title}</h1><p className="public-lead">Project images and outcome figures are awaiting publication review.</p><p className="public-review-note">We are checking source evidence and client permissions before presenting project results. No performance figures or client screenshots are being offered as verified evidence here.</p><div className="public-detail-sections"><section><h2>See how a connection could work</h2><p>The homepage includes a clearly labeled example of organizing an inquiry and preparing a reply for a person to review.</p><Link to="/">Explore the illustrative system →</Link></section></div><nav className="public-related" aria-label="Project records under review">{caseLinks.filter(([,p])=>p!==pathname).map(([name,path])=><Link key={path} to={path}>{name} · Under review</Link>)}<Link to="/portfolio">Portfolio</Link><Link to="/results">Results</Link></nav></section></Layout>}
