import { availability } from '@/components/brand/brandContent';
export { availability };
export const detailPages: Record<string, {title:string;intro:string;status:string;kind:string;sections:[string,string][];related?:[string,string][]}> = {
 '/services/website-development': {title:'A website built around your business.',intro:'Plan, design and build clear pages that help customers understand your business and take the next step.',status:availability,kind:'01',sections:[['Plan the pages','Agree the page structure, content and contact options for your website.'],['Design and build','Create responsive layouts around approved business information and customer needs.'],['Test and hand over','Check navigation, mobile layouts and agreed functionality. Deliverables, timing and ongoing support are defined in the project agreement.']]},
 '/services/ai-lead-capture': {title:'Website development is our current offer.',intro:'AI pilots and AI lead-capture services are not currently offered separately.',status:availability,kind:'03',sections:[['Discuss your website','Explore clear pages and contact options as part of a website project.']]},
 '/services/crm-automation': {title:'CRM integration is not a separate service.',intro:'Our current offer is website development. CRM activation remains unverified; no immediate CRM access is promised.',status:availability,kind:'02',sections:[['Website projects','Discuss your website needs and agree the project scope before work begins.']]},
 '/services/seo-content': {title:'Clear content for your website.',intro:'Page structure and content planning can be discussed as part of website development. We do not currently offer a separate ongoing SEO service.',status:availability,kind:'01',sections:[['Agree the scope','Define the pages, content responsibilities and search foundations in the website project agreement. No ranking or traffic result is promised.']]},
 '/services/paid-advertising': {title:'Website development is our current offer.',intro:'Paid advertising management is not currently offered by MerkadAgency.',status:availability,kind:'01',sections:[['Plan your website','Discuss the pages and contact options your customers need.']]},
 '/industries/medspas': {title:'A clearer path from interest to consultation.',intro:'Plan a website and inquiry process around the way your practice works.',status:availability,kind:'01',sections:[['Explain the service','Make service information, location details and consultation next steps easy to find.'],['Organize inquiries','Plan how general inquiries reach the right person. Do not collect medical details through a general inquiry form.'],['Review before acting','AI-assisted drafts require human review. Booking, reminders and healthcare-specific requirements must be agreed for the project; compliance is not established by this example.']]},
 '/industries/cannabis': {title:'Connect your website and inquiry process.',intro:'Start with clear business information and a reviewed plan for how your team handles questions.',status:availability,kind:'02',sections:[['Clarify the website','Review the information customers need and where each page should lead.'],['Map communication','Identify inquiry channels, ownership and the central customer record.'],['Confirm requirements first','Advertising, age checks, messaging consent and jurisdiction-specific requirements need separate review. No platform eligibility or regulatory compliance is promised.']]},
 '/industries/construction': {title:'Turn project inquiries into a useful first conversation.',intro:'Help prospective customers explain the work they need, then keep the details together for your team.',status:availability,kind:'01',sections:[['Show the work clearly','Structure pages around services and approved project information. Client images are only used with permission.'],['Ask useful questions','Plan inquiry questions around project type, location and the details needed for an initial conversation.'],['Prepare the next step','Explore summaries and draft clarification questions for human review. Estimates, scheduling and automated qualification are separate capabilities to confirm.']]},
 '/industries/ecommerce': {title:'Connect your store to the people behind it.',intro:'Review how your storefront, customer questions and internal tools work together.',status:availability,kind:'02',sections:[['Review the storefront','Make product and service information clear and help visitors find the right next step.'],['Connect customer context','Plan how inquiries and customer records relate to your existing commerce tools. Integrations need project-specific validation.'],['Keep assistance reviewed','Explore summaries and suggested replies with human oversight. Cart recovery, campaigns, revenue attribution and automatic messaging require separate scope and approval.']]},
 '/about': {title:'Technology built around how your team works.',intro:'MerkadAgency designs and builds websites around your customers and your business.',status:availability,kind:'03',sections:[['Start with the work','Understand your customers, your tools and the places where information gets lost.'],['Build something useful','Focus on a clear first project, preserve what already works and explain what is included.'],['Keep responsibility clear','We agree content responsibilities, project scope and support as part of each website project.']],related:[['Our method','/about/method']]},
 '/about/method': {title:'Start small. Make it useful.',intro:'A clear plan for the website, the connections and the people using them.',status:availability,kind:'02',sections:[['01 · Talk it through','Show us your tools and where the process gets frustrating.'],['02 · Make a plan','Agree what we will build, who owns it and how we will know it works.'],['03 · Build and test','Check the forms, permissions and what happens when something goes wrong.'],['04 · Make it yours','Get clear instructions, responsibilities and an agreed support plan.']],related:[['About MerkadAgency','/about']]},
};
export const serviceLinks:[string,string][]=[['Website development','/services/website-development']];
export const industryLinks:[string,string][]=[['Medical spas','/industries/medspas'],['Cannabis','/industries/cannabis'],['Construction','/industries/construction'],['E-commerce','/industries/ecommerce']];
