import { availability } from '@/components/brand/brandContent';
export { availability };
export const detailPages: Record<string, {title:string;intro:string;status:string;kind:string;sections:[string,string][];related?:[string,string][]}> = {
 '/services/ai-lead-capture': {title:'A clearer starting point for every inquiry.',intro:'Build a useful inquiry form and explore AI assistance that organizes the details for your team to review.',status:'Websites available · AI assistance is a human-reviewed pilot',kind:'03',sections:[['Capture the request','Ask for the information your team needs without making the form hard to use.'],['Organize the details','A pilot can explore summaries and suggested replies. Your team reviews the draft and decides what happens next.'],['Connect the next step','CRM integration is in testing. Multi-channel qualification and source attribution are planned capabilities; the tools and responsibilities need to be agreed first.']]},
 '/services/crm-automation': {title:'Keep the customer context together.',intro:'Connect website inquiries to your central CRM so your team can understand the request and take the next step.',status:'CRM integration in testing · Workflow planning available',kind:'02',sections:[['Map your current process','Identify where inquiries arrive, which records your team uses and who owns follow-up.'],['Design the connection','Agree the fields, permissions and handling of incomplete or repeated requests. Connector support is confirmed for each project.'],['Keep people in control','AI can help prepare summaries and drafts in a reviewed pilot. Ongoing communication belongs in the central CRM; automatic follow-up and historical migration require a separate review.']]},
 '/services/seo-content': {title:'Make your website easier to understand.',intro:'Clear page structure and useful content help visitors find the information they need.',status:'Website work available · Ongoing SEO service availability to confirm',kind:'01',sections:[['Page structure','Organize services, headings and navigation around the questions your customers ask.'],['Content planning','Review existing service information, missing explanations and outdated material.'],['Search foundations','Discuss metadata, internal links and technical SEO as part of the website project. Rankings, traffic increases and recurring SEO packages are not confirmed promises.']]},
 '/services/paid-advertising': {title:'Connect the campaign to the customer journey.',intro:'A campaign needs a clear destination and a plan for what happens after someone gets in touch.',status:'Advertising service availability and scope to confirm',kind:'02',sections:[['Review the destination','Check that the landing page explains the offer and provides a useful next step.'],['Plan inquiry ownership','Agree where campaign inquiries go and who reviews them.'],['Define measurement','Discuss conversion tracking, attribution and reporting before campaign work. Platform support, budget and campaign management need separate confirmation; no return on ad spend is promised.']]},
 '/industries/medspas': {title:'A clearer path from interest to consultation.',intro:'Plan a website and inquiry process around the way your practice works.',status:availability,kind:'01',sections:[['Explain the service','Make service information, location details and consultation next steps easy to find.'],['Organize inquiries','Plan how general inquiries reach the right person. Do not collect medical details through a general inquiry form.'],['Review before acting','AI-assisted drafts require human review. Booking, reminders and healthcare-specific requirements must be agreed for the project; compliance is not established by this example.']]},
 '/industries/cannabis': {title:'Connect your website and inquiry process.',intro:'Start with clear business information and a reviewed plan for how your team handles questions.',status:availability,kind:'02',sections:[['Clarify the website','Review the information customers need and where each page should lead.'],['Map communication','Identify inquiry channels, ownership and the central customer record.'],['Confirm requirements first','Advertising, age checks, messaging consent and jurisdiction-specific requirements need separate review. No platform eligibility or regulatory compliance is promised.']]},
 '/industries/construction': {title:'Turn project inquiries into a useful first conversation.',intro:'Help prospective customers explain the work they need, then keep the details together for your team.',status:availability,kind:'01',sections:[['Show the work clearly','Structure pages around services and approved project information. Client images are only used with permission.'],['Ask useful questions','Plan inquiry questions around project type, location and the details needed for an initial conversation.'],['Prepare the next step','Explore summaries and draft clarification questions for human review. Estimates, scheduling and automated qualification are separate capabilities to confirm.']]},
 '/industries/ecommerce': {title:'Connect your store to the people behind it.',intro:'Review how your storefront, customer questions and internal tools work together.',status:availability,kind:'02',sections:[['Review the storefront','Make product and service information clear and help visitors find the right next step.'],['Connect customer context','Plan how inquiries and customer records relate to your existing commerce tools. Integrations need project-specific validation.'],['Keep assistance reviewed','Explore summaries and suggested replies with human oversight. Cart recovery, campaigns, revenue attribution and automatic messaging require separate scope and approval.']]},
 '/about': {title:'Technology built around how your team works.',intro:'MerkadAgency brings websites, CRM integration and AI-assisted workflows into one practical conversation.',status:availability,kind:'03',sections:[['Start with the work','Understand your customers, your tools and the places where information gets lost.'],['Build something useful','Focus on a clear first project, preserve what already works and explain what is included.'],['Keep responsibility clear','People review AI-assisted work and own the next action. We agree responsibilities and support as part of each project.']],related:[['Our method','/about/method']]},
 '/about/method': {title:'Start small. Make it useful.',intro:'A clear plan for the website, the connections and the people using them.',status:availability,kind:'02',sections:[['01 · Talk it through','Show us your tools and where the process gets frustrating.'],['02 · Make a plan','Agree what we will build, who owns it and how we will know it works.'],['03 · Build and test','Check the forms, permissions and what happens when something goes wrong.'],['04 · Make it yours','Get clear instructions, responsibilities and an agreed support plan.']],related:[['About MerkadAgency','/about']]},
};
export const serviceLinks:[string,string][]=[['AI lead capture & assistance','/services/ai-lead-capture'],['CRM integration','/services/crm-automation'],['SEO & content','/services/seo-content'],['Paid advertising','/services/paid-advertising']];
export const industryLinks:[string,string][]=[['Medical spas','/industries/medspas'],['Cannabis','/industries/cannabis'],['Construction','/industries/construction'],['E-commerce','/industries/ecommerce']];
export const caseLinks:[string,string][]=[['Kravings case study','/case-studies/kravings'],['Teonanacatl case study','/case-studies/teonanacatl'],['Grid N Guard case study','/case-studies/gridnguard']];
